export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  );
}

export default RootLayout